import { Teacher } from "@/constants/types";

export const Subjects = [
  {
    id: 1,
    name: 'Maths',
  },
  {
    id: 2,
    name: 'English',
  },
  {
    id: 3,
    name: 'Science',
  },
  {
    id: 4,
    name: 'History',
  },
  {
    id: 5,
    name: 'Geography',
  },
  {
    id: 6,
    name: 'Physics',
  },
  {
    id: 7,
    name: 'Chemistry',
  },
  {
    id: 8,
    name: 'Biology',
  },
  {
    id: 9,
    name: 'Computer Science',
  },
  {
    id: 10,
    name: 'Islamic Studies',
  },
  {
    id: 11,
    name: 'Economics',
  },
  {
    id: 12,
    name: 'Urdu',
  },
  {
    id: 13,
    name: 'Arabic',
  },
  {
    id: 14,
    name: 'Punjabi',
  },
];

export const teachers: Teacher[] = [
  // Teachers within Islamabad
  {
    userId: 1,
    fullName: "Sara Ahmed",
    courses: ["Math", "Science"],
    longitude: 73.0479,
    latitude: 33.6844,
    hourlyRate: 30,
    rating: 4,
    totalClasses: 50,
    totalStudents: 25,
    totalHours: 150,
    totalReviews: 20,
    subject: "English",
    gender: "Female",
    profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
  },
  {
    userId: 2,
    fullName: "Ahmed Khan",
    courses: ["Physics", "Chemistry"],
    longitude: 73.0551,
    latitude: 33.6843,
    hourlyRate: 35,
    rating: 4.5,
    totalClasses: 60,
    totalStudents: 30,
    totalHours: 180,
    totalReviews: 25,
    subject: "Maths",
    gender: "Male",
    profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
  },
  {
    userId: 3,
    fullName: "Ayesha Malik",
    courses: ["Biology", "Geography"],
    longitude: 73.0650,
    latitude: 33.6842,
    hourlyRate: 40,
    rating: 4.2,
    totalClasses: 45,
    totalStudents: 20,
    totalHours: 120,
    totalReviews: 18,
    subject: "Urdu",
    gender: "Female",
    profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
  },
  {
    userId: 4,
    fullName: "Farhan Abbas",
    courses: ["History", "Economics"],
    longitude: 73.0545,
    latitude: 33.6839,
    hourlyRate: 25,
    rating: 3.8,
    totalClasses: 40,
    totalStudents: 15,
    totalHours: 100,
    totalReviews: 15,
    subject: "Physics",
    gender: "Male",
    profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
  },
  {
    userId: 5,
    fullName: "Nida Azam",
    courses: ["English", "Computer Science"],
    longitude: 73.0590,
    latitude: 33.6847,
    hourlyRate: 35,
    rating: 4.7,
    totalClasses: 55,
    totalStudents: 28,
    totalHours: 160,
    totalReviews: 22,
    subject: "Islamic Studies",
    gender: "Female",
    profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg"
  },

  // Teachers from other cities
  {
    userId: 6,
    fullName: "Ali Khan",
    courses: ["English", "History"],
    longitude: 67.0011, // Sample longitude for another city
    latitude: 24.8607, // Sample latitude for another city
    hourlyRate: 40,
    rating: 5,
    totalClasses: 75,
    totalStudents: 30,
    totalHours: 180,
    totalReviews: 25,
    subject: "Punjabi",
    gender: "Male",
    profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
  },
  {
    userId: 7,
    fullName: "Zainab Malik",
    courses: ["Chemistry", "Physics"],
    longitude: 71.5249,
    latitude: 32.5735,
    hourlyRate: 45,
    rating: 4.9,
    totalClasses: 65,
    totalStudents: 32,
    totalHours: 190,
    totalReviews: 28,
    subject: "Chemistry",
    gender: "Female",
    profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
  },
  {
    userId: 8,
    fullName: "Muneeb Ahmed",
    courses: ["Math", "Computer Science"],
    longitude: 68.3346,
    latitude: 25.0812,
    hourlyRate: 30,
    rating: 4.4,
    totalClasses: 55,
    totalStudents: 25,
    totalHours: 160,
    totalReviews: 20,
    subject: "Computer Science",
    gender: "Male",
    profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
  },
  {
    userId: 9,
    fullName: "Fariha Akhtar",
    courses: ["Biology", "Geography"],
    longitude: 74.3587,
    latitude: 32.4395,
    hourlyRate: 35,
    rating: 4.2,
    totalClasses: 48,
    totalStudents: 22,
    totalHours: 130,
    totalReviews: 18,
    subject: "Arabic",
    gender: "Female",
    profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
  },
  {
    userId: 10,
    fullName: "Asad Ali",
    courses: ["History", "Economics"],
    longitude: 70.2598,
    latitude: 28.6139,
    hourlyRate: 40,
    rating: 3.9,
    totalClasses: 42,
    totalStudents: 18,
    totalHours: 110,
    totalReviews: 16,
    subject: "Maths",
    gender: "Male",
    profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
  },
]


// let abc = db.teachers.insertMany([
//   {
//     userId: ObjectId('65e06790e93f33d690eedba8'),
//     fullName: "Ahmed Khan",
//     courses: ["Physics", "Chemistry"],
//     longitude: 73.0551,
//     latitude: 33.6843,
//     hourlyRate: 35,
//     rating: 4.5,
//     totalClasses: 60,
//     totalStudents: 30,
//     totalHours: 180,
//     totalReviews: 25,
//     subject: "Maths",
//     gender: "Male",
//     profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067a5e93f33d690eedbab'),
//     fullName: "Ayesha Malik",
//     courses: ["Biology", "Geography"],
//     longitude: 73.0650,
//     latitude: 33.6842,
//     hourlyRate: 40,
//     rating: 4.2,
//     totalClasses: 45,
//     totalStudents: 20,
//     totalHours: 120,
//     totalReviews: 18,
//     subject: "Urdu",
//     gender: "Female",
//     profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067b2e93f33d690eedbae'),
//     fullName: "Farhan Abbas",
//     courses: ["History", "Economics"],
//     longitude: 73.0545,
//     latitude: 33.6839,
//     hourlyRate: 25,
//     rating: 3.8,
//     totalClasses: 40,
//     totalStudents: 15,
//     totalHours: 100,
//     totalReviews: 15,
//     subject: "Physics",
//     gender: "Male",
//     profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067c2e93f33d690eedbb1'),
//     fullName: "Nida Azam",
//     courses: ["English", "Computer Science"],
//     longitude: 73.0590,
//     latitude: 33.6847,
//     hourlyRate: 35,
//     rating: 4.7,
//     totalClasses: 55,
//     totalStudents: 28,
//     totalHours: 160,
//     totalReviews: 22,
//     subject: "Islamic Studies",
//     gender: "Female",
//     profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg"
//   },
//   {
//     userId: ObjectId('65e067cee93f33d690eedbb4'),
//     fullName: "Ali Khan",
//     courses: ["English", "History"],
//     longitude: 67.0011, // Sample longitude for another city
//     latitude: 24.8607, // Sample latitude for another city
//     hourlyRate: 40,
//     rating: 5,
//     totalClasses: 75,
//     totalStudents: 30,
//     totalHours: 180,
//     totalReviews: 25,
//     subject: "Punjabi",
//     gender: "Male",
//     profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067d8e93f33d690eedbb7'),
//     fullName: "Zainab Malik",
//     courses: ["Chemistry", "Physics"],
//     longitude: 71.5249,
//     latitude: 32.5735,
//     hourlyRate: 45,
//     rating: 4.9,
//     totalClasses: 65,
//     totalStudents: 32,
//     totalHours: 190,
//     totalReviews: 28,
//     subject: "Chemistry",
//     gender: "Female",
//     profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067e2e93f33d690eedbba'),
//     fullName: "Muneeb Ahmed",
//     courses: ["Math", "Computer Science"],
//     longitude: 68.3346,
//     latitude: 25.0812,
//     hourlyRate: 30,
//     rating: 4.4,
//     totalClasses: 55,
//     totalStudents: 25,
//     totalHours: 160,
//     totalReviews: 20,
//     subject: "Computer Science",
//     gender: "Male",
//     profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067ebe93f33d690eedbbd'),
//     fullName: "Fariha Akhtar",
//     courses: ["Biology", "Geography"],
//     longitude: 74.3587,
//     latitude: 32.4395,
//     hourlyRate: 35,
//     rating: 4.2,
//     totalClasses: 48,
//     totalStudents: 22,
//     totalHours: 130,
//     totalReviews: 18,
//     subject: "Arabic",
//     gender: "Female",
//     profileImg: "https://static.vecteezy.com/system/resources/previews/008/437/407/original/female-icon-for-website-symbol-presentation-free-vector.jpg",
//   },
//   {
//     userId: ObjectId('65e067f3e93f33d690eedbc0'),
//     fullName: "Asad Ali",
//     courses: ["History", "Economics"],
//     longitude: 70.2598,
//     latitude: 28.6139,
//     hourlyRate: 40,
//     rating: 3.9,
//     totalClasses: 42,
//     totalStudents: 18,
//     totalHours: 110,
//     totalReviews: 16,
//     subject: "Maths",
//     gender: "Male",
//     profileImg: "https://static.vecteezy.com/system/resources/thumbnails/006/487/917/small/man-avatar-icon-free-vector.jpg",
//   },
// ])